---
- name: Gather facts for conditional playbook imports
  hosts: all
  become: true
  gather_facts: true
  
- import_playbook: ceph-osdnvm1-wal-partition.yaml
  when: ansible_hostname == "ceph-osdnvm1-c7-33-fl"

- import_playbook: ceph-osdnvm1-db-partition.yaml
  when: ansible_hostname == "ceph-osdnvm1-c7-33-fl"
