---
- name: nvme partitions using parted module
  hosts: all
  become: true
  tasks:
    - name: Read device information of /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        unit: GB
      register: before_part

    - name: Print Device info of /dev/nvme0n1
      debug:
        msg: "{{ before_part }}"

    - name: Create a 1st partition on /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        number: 1
        label: gpt
        name: "wal for /dev/sdb"
        state: present
        part_start: "0%"
        part_end: "5%"

    - name: Create a 2nd partition on /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        number: 2
        label: gpt
        name: "wal for /dev/sdc"
        state: present
        part_start: "5%"
        part_end: "10%"

    - name: Create a 3rd partition on /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        number: 3
        label: gpt
        name: "wal for /dev/sdd"
        state: present
        part_start: "10%"
        part_end: "15%"

    - name: Create a 4th partition on /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        number: 4
        label: gpt
        name: "wal for /dev/sde"
        state: present
        part_start: "15%"
        part_end: "20%"

    - name: Create a 5th partition on /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        number: 5
        label: gpt
        name: "wal for /dev/sdf"
        state: present
        part_start: "20%"
        part_end: "25%"

    - name: Create a 6th partition on /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        number: 6
        label: gpt
        name: "wal for /dev/sdg"
        state: present
        part_start: "25%"
        part_end: "30%"

    - name: Create a 7th partition on /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        number: 7
        label: gpt
        name: "wal for /dev/sdh"
        state: present
        part_start: "30%"
        part_end: "35%"

    - name: Create a 8th partition on /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        number: 8
        label: gpt
        name: "wal for /dev/sdj"
        state: present
        part_start: "35%"
        part_end: "40%"

    - name: Create a 9th partition on /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        number: 9
        label: gpt
        name: "wal for /dev/sdk"
        state: present
        part_start: "40%"
        part_end: "45%"

    - name: Create a 10th partition on /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        number: 10
        label: gpt
        name: "wal for /dev/sdl"
        state: present
        part_start: "45%"
        part_end: "50%"

    - name: Create a 11th partition on /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        number: 11
        label: gpt
        name: "wal for /dev/sdm"
        state: present
        part_start: "50%"
        part_end: "55%"

    - name: Create a 12th partition on /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        number: 12
        label: gpt
        name: "wal for /dev/sdn"
        state: present
        part_start: "55%"
        part_end: "60%"

    - name: Create a 13th partition on /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        number: 13
        label: gpt
        name: "wal for /dev/sdo"
        state: present
        part_start: "60%"
        part_end: "65%"

    - name: Create a 14th partition on /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        number: 14
        label: gpt
        name: "wal for /dev/sdp"
        state: present
        part_start: "65%"
        part_end: "70%"

    - name: Create a 15th partition on /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        number: 15
        label: gpt
        name: "wal for /dev/sdq"
        state: present
        part_start: "70%"
        part_end: "75%"

    - name: Create a 16th partition on /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        number: 16
        label: gpt
        name: "wal for /dev/sdr"
        state: present
        part_start: "75%"
        part_end: "80%"

    - name: Read device information of /dev/nvme0n1
      parted:
        device: /dev/nvme0n1
        unit: GB
      register: after_part

    - name: Print Device info of /dev/nvme0n1
      debug:
        msg: "{{ after_part }}"
