---
- name: nvme partitions using parted module
  hosts: all
  become: true
  tasks:
    - name: Read device information
      parted:
        device: /dev/nvme0n1
        unit: MiB
      register: info_nvme0n1

    - name: Print Device info {{ ansible_hostname }}
      debug:
        var: "{{ info_nvme0n1 }}"

    - name: Create a new primary partition
      parted:
        device: /dev/nvme0n1
        number: 1
        label: gpt
        name: "Journal for /dev/sdb"
        state: present
        part_start: "0"
        part_end: "5"
        unit: %

    - name: Read device information
      parted:
        device: /dev/nvme0n1
        unit: MiB
      register: info_nvme0n1

    - name: Print Device info {{ ansible_hostname }}
      debug:
        var: "{{ info_nvme0n1 }}"
