---
- name: nvme partitions using parted module
  hosts: all
  become: true
  tasks:
    - name: Running debug to check ansible run on {{ ansible_hostname }}
      debug:
        msg: "Running parted on ansible_hostname"
