---
- name: nvme partitions using parted module
  hosts: all
  become: true
  tasks:
    # - name: Running debug to check ansible run on {{ ansible_hostname }}
    #   debug:
    #     msg: "Running parted on {{ ansible_hostname }}"

    - name: Read device information
      parted:
        device: /dev/nvme0n1
        unit: MiB
      register: info_nvme0n1

    - name: Print Device info {{ ansible_hostname }}
      debug:
        var: {{ info_nvme0n1 }}

    - name: Create a new primary partition
      parted:
        device: /dev/nvme0n1
        number: 16
        state: present

    - name: Read device information
      parted:
        device: /dev/nvme0n1
        unit: MiB
      register: info_nvme0n1
      
    - name: Print Device info {{ ansible_hostname }}
      debug:
        var: {{ info_nvme0n1 }}
